-- MySQL Script generated by MySQL Workbench
-- Fri 24 Jan 2020 16:19:04 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `idpatient` INT UNSIGNED NOT NULL,
  `patient_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`idpatient`),
  UNIQUE INDEX `idpatient_UNIQUE` (`idpatient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gene` (
  `idgene` INT NOT NULL,
  `gene_name` VARCHAR(45) NULL,
  `start` INT NULL,
  `stop` INT NULL,
  `chromosome` VARCHAR(45) NULL,
  `description_gene` VARCHAR(450) NULL,
  PRIMARY KEY (`idgene`),
  UNIQUE INDEX `idgene_UNIQUE` (`idgene` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`syndrome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`syndrome` (
  `syndrome_name` INT NOT NULL,
  `description_syndrome` VARCHAR(450) NULL,
  PRIMARY KEY (`syndrome_name`),
  UNIQUE INDEX `syndrome_name_UNIQUE` (`syndrome_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diagnose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnose` (
  `iddiagnose` INT NOT NULL,
  `syndrome_name` VARCHAR(45) NULL,
  `age_patient` INT NULL,
  `patient_id` VARCHAR(45) NULL,
  `patient_idpatient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iddiagnose`, `patient_idpatient`),
  UNIQUE INDEX `iddiagnose_UNIQUE` (`iddiagnose` ASC) VISIBLE,
  INDEX `fk_diagnose_patient1_idx` (`patient_idpatient` ASC) VISIBLE,
  CONSTRAINT `patient_id`
    FOREIGN KEY (`patient_idpatient`)
    REFERENCES `mydb`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diagnose_has_syndrome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnose_has_syndrome` (
  `diagnose_iddiagnose` INT NOT NULL,
  `syndrome_syndrome_name` INT NOT NULL,
  PRIMARY KEY (`diagnose_iddiagnose`, `syndrome_syndrome_name`),
  INDEX `fk_diagnose_has_syndrome_syndrome1_idx` (`syndrome_syndrome_name` ASC) VISIBLE,
  INDEX `fk_diagnose_has_syndrome_diagnose_idx` (`diagnose_iddiagnose` ASC) VISIBLE,
  CONSTRAINT `fk_diagnose_has_syndrome_diagnose`
    FOREIGN KEY (`diagnose_iddiagnose`)
    REFERENCES `mydb`.`diagnose` (`iddiagnose`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnose_has_syndrome_syndrome1`
    FOREIGN KEY (`syndrome_syndrome_name`)
    REFERENCES `mydb`.`syndrome` (`syndrome_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`syndrome_has_gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`syndrome_has_gene` (
  `syndrome_syndrome_name` INT NOT NULL,
  `gene_idgene` INT NOT NULL,
  PRIMARY KEY (`syndrome_syndrome_name`, `gene_idgene`),
  INDEX `fk_syndrome_has_gene_gene1_idx` (`gene_idgene` ASC) VISIBLE,
  INDEX `fk_syndrome_has_gene_syndrome1_idx` (`syndrome_syndrome_name` ASC) VISIBLE,
  CONSTRAINT `fk_syndrome_has_gene_syndrome1`
    FOREIGN KEY (`syndrome_syndrome_name`)
    REFERENCES `mydb`.`syndrome` (`syndrome_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_syndrome_has_gene_gene1`
    FOREIGN KEY (`gene_idgene`)
    REFERENCES `mydb`.`gene` (`idgene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
